### PR TITLE
remove projects folder from incuna-sass

### PR DESCRIPTION
**Pull request by hippogriffic**
To be moved to a closed source project library

@incuna/frontend please review

### CODE REVIEW

**Comment by pandalion** [comment]
This should be fine when https://github.com/incuna/incuna-epatient-web/pull/284 is finalised :)

**Comment by hippogriffic** [comment]
@incuna/frontend can this be merged? It would be good to do it before #51

**Comment by maciejpi** [comment]
I'm not deleting the branch as for now - just in case if someone decides we should revert this commit:)

**Comment by henrahmagix** [comment]
@maciejpi GitHub allows easy reverting of merged pull-requests even after the branch is deleted.

**Pull request merged**
