### PR TITLE
Update version of necolas' normalize to 7.0.0

### PR DESCRIPTION
**Pull request by pandalion**

### CODE REVIEW

**Comment by perry** [comment]
screen shot 2017-05-17 at 4 40 10 pm

Accident! 😨

**Comment by pandalion** [comment]
:O @perry !

**Comment by pandalion** [comment]
But good idea. @hippogriffic please review :D

**Comment by hippogriffic** [comment]
reviewed

I give you the green tick of approval

**Comment by wytrych** [comment]
👍

**Comment by hippogriffic** [comment]
aww it's like a little reunion :D

**Pull request merged**
